/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Sun Jan  5 21:36:23 2020. */

#include "protocol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Hello_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Hello, versionMajor, versionMajor, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Hello, versionMinor, versionMajor, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, Hello, versionLast, versionMinor, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, Hello, screenEnabled, versionLast, 0),
    PB_FIELD(  5, STRING  , REQUIRED, CALLBACK, OTHER, Hello, settings, screenEnabled, 0),
    PB_LAST_FIELD
};

const pb_field_t Relay_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Relay, id, id, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, Relay, state, id, 0),
    PB_LAST_FIELD
};

const pb_field_t ParsedRemote_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, ParsedRemote, remote, remote, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, ParsedRemote, key, remote, 0),
    PB_LAST_FIELD
};

const pb_field_t Msg_fields[15] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Msg, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Msg, timeseq, id, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, Msg, hello, timeseq, &Hello_fields),
    PB_FIELD(  4, UINT32  , REPEATED, CALLBACK, OTHER, Msg, irKeyPeriods, hello, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, Msg, debugLogMessage, irKeyPeriods, 0),
    PB_FIELD(  6, MESSAGE , REPEATED, STATIC  , OTHER, Msg, relayStates, debugLogMessage, &Relay_fields),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, Msg, parsedRemote, relayStates, &ParsedRemote_fields),
    PB_FIELD(  8, BOOL    , OPTIONAL, STATIC  , OTHER, Msg, buttonPressed, parsedRemote, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, Msg, weight, buttonPressed, 0),
    PB_FIELD( 10, FLOAT   , OPTIONAL, STATIC  , OTHER, Msg, temp, weight, 0),
    PB_FIELD( 11, FLOAT   , OPTIONAL, STATIC  , OTHER, Msg, humidity, temp, 0),
    PB_FIELD( 12, FLOAT   , OPTIONAL, STATIC  , OTHER, Msg, pressure, humidity, 0),
    PB_FIELD( 13, UINT32  , OPTIONAL, STATIC  , OTHER, Msg, potentiometer, pressure, 0),
    PB_FIELD( 14, BOOL    , OPTIONAL, STATIC  , OTHER, Msg, atxState, potentiometer, 0),
    PB_LAST_FIELD
};

const pb_field_t MsgBack_fields[23] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, MsgBack, id, id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, MsgBack, testMsg, id, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, MsgBack, unixtime, testMsg, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, MsgBack, textToShow, unixtime, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, MsgBack, timeMsToShow, textToShow, 0),
    PB_FIELD(  7, UENUM   , OPTIONAL, STATIC  , OTHER, MsgBack, showType, timeMsToShow, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, MsgBack, relaysToSwitch, showType, 0),
    PB_FIELD(  9, BOOL    , OPTIONAL, STATIC  , OTHER, MsgBack, relaysToSwitchState, relaysToSwitch, 0),
    PB_FIELD( 10, BOOL    , OPTIONAL, STATIC  , OTHER, MsgBack, atxEnable, relaysToSwitchState, 0),
    PB_FIELD( 11, UINT32  , OPTIONAL, STATIC  , OTHER, MsgBack, playMp3, atxEnable, 0),
    PB_FIELD( 12, UINT32  , OPTIONAL, STATIC  , OTHER, MsgBack, volume, playMp3, 0),
    PB_FIELD( 13, UINT32  , OPTIONAL, STATIC  , OTHER, MsgBack, brightness, volume, 0),
    PB_FIELD( 14, UINT32  , OPTIONAL, STATIC  , OTHER, MsgBack, pwmPin, brightness, 0),
    PB_FIELD( 15, UINT32  , OPTIONAL, STATIC  , OTHER, MsgBack, pwmValue, pwmPin, 0),
    PB_FIELD( 16, UINT32  , OPTIONAL, STATIC  , OTHER, MsgBack, pwmPeriod, pwmValue, 0),
    PB_FIELD( 17, STRING  , OPTIONAL, CALLBACK, OTHER, MsgBack, ledValue, pwmPeriod, 0),
    PB_FIELD( 18, UINT32  , OPTIONAL, STATIC  , OTHER, MsgBack, ledPeriod, ledValue, 0),
    PB_FIELD( 19, STRING  , OPTIONAL, CALLBACK, OTHER, MsgBack, ledBaseColor, ledPeriod, 0),
    PB_FIELD( 20, STRING  , OPTIONAL, CALLBACK, OTHER, MsgBack, ledBlinkColors, ledBaseColor, 0),
    PB_FIELD(200, BOOL    , OPTIONAL, STATIC  , OTHER, MsgBack, introduceYourself, ledBlinkColors, 0),
    PB_FIELD(201, BOOL    , OPTIONAL, STATIC  , OTHER, MsgBack, reboot, introduceYourself, 0),
    PB_FIELD(202, BOOL    , OPTIONAL, STATIC  , OTHER, MsgBack, screenEnable, reboot, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Msg, hello) < 65536 && pb_membersize(Msg, relayStates[0]) < 65536 && pb_membersize(Msg, parsedRemote) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Hello_Relay_ParsedRemote_Msg_MsgBack)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Msg, hello) < 256 && pb_membersize(Msg, relayStates[0]) < 256 && pb_membersize(Msg, parsedRemote) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Hello_Relay_ParsedRemote_Msg_MsgBack)
#endif


/* @@protoc_insertion_point(eof) */
