/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Hello, Hello, AUTO)


PB_BIND(Relay, Relay, AUTO)


PB_BIND(ParsedRemote, ParsedRemote, AUTO)


PB_BIND(Msg, Msg, 2)


PB_BIND(ScreenOffset, ScreenOffset, AUTO)


PB_BIND(ScreenContent, ScreenContent, AUTO)


PB_BIND(BluePill, BluePill, AUTO)


PB_BIND(MsgBack, MsgBack, 2)




