/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Thu Jan  2 15:45:24 2020. */

#include "protocol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Settings_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, Settings, name, name, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, Settings, rus_name, name, 0),
    PB_LAST_FIELD
};

const pb_field_t Hello_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Hello, versionMajor, versionMajor, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Hello, versionMinor, versionMajor, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, Hello, versionLast, versionMinor, 0),
    PB_FIELD(  4, MESSAGE , REQUIRED, STATIC  , OTHER, Hello, settings, versionLast, &Settings_fields),
    PB_LAST_FIELD
};

const pb_field_t Msg_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Msg, id, id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Msg, timeseq, id, 0),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, Msg, hello, timeseq, &Hello_fields),
    PB_FIELD(  4, INT32   , REPEATED, STATIC  , OTHER, Msg, irKeyPeriods, hello, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Hello, settings) < 65536 && pb_membersize(Msg, hello) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Settings_Hello_Msg)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for Msg.irKeyPeriods is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
